# Generated by Django 5.2.7 on 2025-10-31 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flyers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flyer",
            name="description",
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
